package com.volokhinaleksey.kash.theme

import androidx.compose.ui.graphics.Color

// Nordic Alabaster (Light)
val LightPrimary = Color(0xFF3E6658)
val LightOnPrimary = Color(0xFFFFFFFF)
val LightPrimaryContainer = Color(0xFF8FB9A8)
val LightOnPrimaryContainer = Color(0xFF1A3329)
val LightSecondary = Color(0xFF8B4B56)
val LightOnSecondary = Color(0xFFFFFFFF)
val LightSecondaryContainer = Color(0xFFFFAEBA)
val LightOnSecondaryContainer = Color(0xFF390916)
val LightTertiary = Color(0xFFDBA29D)
val LightOnTertiary = Color(0xFF3E2420)
val LightTertiaryContainer = Color(0xFFFFD9DD)
val LightOnTertiaryContainer = Color(0xFF390916)
val LightSurface = Color(0xFFF9F9FB)
val LightOnSurface = Color(0xFF1A1C1D)
val LightSurfaceVariant = Color(0xFFF3F3F5)
val LightOnSurfaceVariant = Color(0xFF44474A)
val LightSurfaceContainerLowest = Color(0xFFFFFFFF)
val LightSurfaceContainerLow = Color(0xFFF3F3F5)
val LightSurfaceContainer = Color(0xFFEDEDF0)
val LightSurfaceContainerHigh = Color(0xFFE7E7EA)
val LightSurfaceContainerHighest = Color(0xFFE1E2E5)
val LightOutlineVariant = Color(0xFFC4C7CA)
val LightBackground = Color(0xFFF9F9FB)
val LightOnBackground = Color(0xFF1A1C1D)
val LightError = Color(0xFFBA1A1A)
val LightOnError = Color(0xFFFFFFFF)

// Nordic Slate (Dark)
val DarkPrimary = Color(0xFF8FB9A8)
val DarkOnPrimary = Color(0xFF1A3329)
val DarkPrimaryContainer = Color(0xFF3E6658)
val DarkOnPrimaryContainer = Color(0xFFB5E0CF)
val DarkSecondary = Color(0xFFFFAEBA)
val DarkOnSecondary = Color(0xFF5C1628)
val DarkSecondaryContainer = Color(0xFF8B4B56)
val DarkOnSecondaryContainer = Color(0xFFFFD9DD)
val DarkTertiary = Color(0xFFDBA29D)
val DarkOnTertiary = Color(0xFF3E2420)
val DarkTertiaryContainer = Color(0xFF5C3B36)
val DarkOnTertiaryContainer = Color(0xFFFFD9DD)
val DarkSurface = Color(0xFF121212)
val DarkOnSurface = Color(0xFFE0E0E0)
val DarkSurfaceVariant = Color(0xFF2D2D44)
val DarkOnSurfaceVariant = Color(0xFFC4C7CA)
val DarkSurfaceContainerLowest = Color(0xFF0D0D0D)
val DarkSurfaceContainerLow = Color(0xFF1A1A2E)
val DarkSurfaceContainer = Color(0xFF1E1E2E)
val DarkSurfaceContainerHigh = Color(0xFF272738)
val DarkSurfaceContainerHighest = Color(0xFF2D2D44)
val DarkOutlineVariant = Color(0xFF44474A)
val DarkBackground = Color(0xFF121212)
val DarkOnBackground = Color(0xFFE0E0E0)
val DarkError = Color(0xFFFFB4AB)
val DarkOnError = Color(0xFF690005)

// Semantic colors (shared)
val IncomeGreen = Color(0xFF8FB9A8)
val ExpensePink = Color(0xFFFFAEBA)
